url: http://www.centreofsense.com
baseurl: ""

# Site settings
title: Centre of Sense
tab_subtitle: A somatic integration

email: hello@centreofsense.com

timeline:
- item: how
  img: how.jpg
- item: approach
  img: approach.jpg
- item: benefits
  img: benefits.jpg

offers:
- item: rolfing
  modal-id: rolfing
  img: rolfing.jpg
  thumbnail: rolfing-thumbnail.jpg

- item: embodied-counselling
  modal-id: embodied-counselling
  img: embodied-counselling.jpg
  thumbnail: embodied-counselling-thumbnail.jpg

- item: sex-intimacy-coaching
  modal-id: sex-intimacy-coaching
  img: sex-intimacy-coaching.jpg
  thumbnail: sex-intimacy-coaching-thumbnail.jpg

- item: in-person
  modal-id: in-person
  img: session.jpg
  thumbnail: session-thumbnail.jpg

- item: corporate
  modal-id: corporate
  img: corporate.jpg
  thumbnail: corporate-thumbnail.jpg

- item: workshops
  modal-id: workshops
  img: workshop.jpg
  thumbnail: workshop-thumbnail.jpg

# Team names, titles and social links
people:
- name: Georgia Grace
  pic: georgia
  description: entry_georgia
  social:
    - title: globe
      url: https://www.georgiagraced.com
    - title: envelope
      url: mailto:georgia@centreofsense.com
- name: Celeste Carrillo
  pic: celeste
  description: entry_celeste
  social:
    - title: globe
      url: http://www.somaticbalance.com.au/
    - title: envelope
      url: mailto:cele@centreofsense.com

social:
  - title: facebook
    url: https://www.facebook.com/CentreOfSense
  - title: linkedin
    url: https://www.linkedin.com/company/centre-of-sense/


# Build settings
markdown: kramdown
permalink: pretty