url: http://www.centreofsense.com
baseurl: ""

# Default language
lang: en

languages:
  en: English

# Site settings
full_title: "Centre of Sense: A somatic meditation"
title: Centre of Sense #TODO se puede poner que diga algo mas en la tab del browser?
email: info@yogestalt.com #TODO change


timeline:
- item: traditional_practices
  img: how.jpg
- item: intention
  img: approach.jpg
- item: practice
  img: benefits.jpg
angas:
- item: asana
  modal-id: 1
  img: session.jpg
  thumbnail: session-thumbnail.jpg

- item: mudra
  modal-id: 2
  img: corporate.jpg
  thumbnail: corporate-thumbnail.jpg

- item: pranayama
  modal-id: 3
  img: workshop.jpg
  thumbnail: workshop-thumbnail.jpg

# Team names, titles and social links
people:
- name: Georgia Grace
  pic: georgia
  description: entry_georgia
  social:
    - title: globe
      #TODO cambiar url georgia
      url: http://blog.yogestalt.com
    - title: envelope
      url: mailto:info@georgiagraced.com
- name: Celeste Carrillo
  pic: celeste
  description: entry_celeste
  social:
    - title: globe
      url: http://www.somaticbalance.com.au/
    - title: envelope
      url: mailto:cele@somaticbalance.com.au


# Build settings
markdown: kramdown
permalink: pretty